### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mariospapaz** [mariospapaz/dwm#1]
- [x] run autostart script automatically
- [x] run statusbar script automatically 
- [x] Setup audio
- [x] Add Audio device in status bar
